'use strict'

module.exports.nats = {
  url: '', // example: nats://USERNAME:PASSWORD@localhost:4222
  clusterID: 'test-cluster',
  subject: 'share-it',
};

module.exports.sns = {
  clientID: 'awsClient',
  region: 'us-east-1',
  topicARN: '', // example: arn:aws:sns:us-east-1:12312312323:snstopicname
  port: 4444,
  prefix: "aws.",
  secret_key: "", // random secret key
};

module.exports.eventgrid = {
  clientID: 'azureClient',
  url: '', // example: https://shareit-hierarchie.westus2-1.eventgrid.azure.net/api/events
  key: '', // event grid access key, generated by azure
  port: 4445,
  prefix: "azure.",
  secret_key: "", // another random secret key
};
